projectname    GumEngine

srcdir         src
exampledir     examples

findlibraries  OpenGL X11.bsd X11.linux SELF GumGUI GumEssentials GumOpenGL GumCodecs GumPrimitives GumDesktop GumSystem GumGLFW GumMaths
headerfiles    gum-engine Engine/2D/ Engine/2D/Layer/ Engine/3D/ Engine/3D/Object/ Engine/3D/Object/Skeletal/ Engine/3D/Lightning/ Engine/General/ Engine/Rendering/ Engine/Lightning/ Engine/Lightning/ShadowMapping/ Engine/Loaders/ Engine/Managers/ Engine/Material/ Engine/Particle/ Engine/Physics/ Engine/PostProcessing/ Engine/PostProcessing/Effects/ Engine/PostProcessing/ImageCorrection/ Engine/PostProcessing/OutlineRenderer/ Engine/Texture/ Engine/Shaders/
examples       Examples

extralibraries_begin
    freetype
    minizip
extralibraries_end

extraincludepaths_begin
    PROJECTROOT/external/bullet3/src/
extraincludepaths_end

customstr_begin
set(BUILD_PYBULLET OFF CACHE INTERNAL "")
set(BUILD_CPU_DEMOS OFF CACHE INTERNAL "")
set(BUILD_OPENGL3_DEMOS OFF CACHE INTERNAL "")
set(BUILD_BULLET2_DEMOS OFF CACHE INTERNAL "")
set(BUILD_EXTRAS OFF CACHE INTERNAL "")
set(BUILD_UNIT_TESTS OFF CACHE INTERNAL "")

add_subdirectory(${CMAKE_SOURCE_DIR}/external/bullet3/ EXCLUDE_FROM_ALL)
customstr_end

tocombinetargets_begin
    BulletSoftBody
    BulletDynamics
    BulletCollision
    LinearMath
tocombinetargets_end